export const ADICIONA_PROJETO = 'ADICIONA_PROJETO'
export const ALTERA_PROJETO = 'ALTERA_PROJETO'
export const REMOVE_PROJETO = 'REMOVE_PROJETO'
export const ADICIONA_TAREFA = 'ADICIONA_TAREFA'
export const REMOVE_TAREFA = 'REMOVE_TAREFA'
export const LIMPA_TODAS_TAREFAS = 'REMOVE_TODAS_TAREFAS'

export const DEFINIR_PROJETOS = 'DEFINIR_PROJETOS'

export const NOTIFICAR = 'NOTIFICA'

export const DEFINIR_TAREFAS = 'DEFINIR_TAREFAS'
export const ADICIONAR_TAREFA = 'ADICIONAR_TAREFA'
export const ALTERA_TAREFA = 'ALTERA_TAREFA'