export const ADICIONA_PROJETO = 'ADICIONA_PROJETO'
export const ALTERA_PROJETO = 'ALTERA_PROJETO'
export const REMOVE_PROJETO = 'REMOVE_PROJETO'
export const ADICIONA_TAREFA = 'ADICIONA_TAREFA'
export const DEFINIR_PROJETOS = 'DEFINIR_PROJETOS'

export const NOTIFICAR = 'NOTIFICA'